# file: kho_kich_ban.py

SCENARIOS = {
    # --- Kịch bản buổi sáng (8h - 10h) ---
    "morning": [
        "sáng anh em",
        "anh em nào dậy sớm thế",
        "vừa vào thua ngay tay đầu chán thật",
        "làm ly cafe cho tỉnh táo rồi vào việc",
        "đêm qua có ai húp không tôi ngủ sớm quá",
        "nay chơi nhỏ nhẹ thôi xem cầu kèo thế nào đã",
        "vào phát ăn ngay tay đầu tiên ngon",
        "bàn này cầu mới để tôi ngồi xem tí",
        "mạng mẽo sáng ra đã lag rồi",
        "có ai đang chơi không cho tôi theo với",
        "chào buổi sáng nhé cả nhà",
        "tôi vào kiếm bát phở đây",
        "mở bát thua rồi báo hiệu một ngày khó khăn",
        "cầu sáng sớm có vẻ êm đềm nhỉ",
        "anh em nào có cầu đẹp hú tôi với",
        "vừa ngủ dậy tay chân còn run quá",
        "chưa dám vào tiền mạnh đâu",
        "thấy có cầu bệt rồi không biết có nên theo không",
        "mới sáng sớm mà đã cuốn rồi",
        "mục tiêu hôm nay kiếm 5 lít thôi",
        "vào việc thôi anh em ơi",
        "đêm qua nằm mơ đẹp nay chắc hên",
        "lại là một ngày xa bờ nữa chăng",
        "bàn này trông quen quen",
        "thôi cứ bình tĩnh mà chơi",
        "vào vốn từ từ thôi không vội được",
        "sáng ra đã thấy nhóm xôm rồi",
        "tôi ngồi hóng anh em chơi đã",
        "vừa nạp thêm ít lúa để chiến đây",
        "cầu kèo trông chưa rõ ràng lắm",
        "chơi vài tay giải đen buổi sáng xem nào",
        "sao mạng cứ quay vòng vòng thế này",
        "húp non được một tay rồi",
        "có ai đang chơi bàn 9 không",
        "chúc anh em ngày mới rực rỡ nhé",
        "tôi xin phép mở bát trước đây",
        "nay mà thua nữa chắc nghỉ một thời gian",
        "vừa tỉnh ngủ vào xem nhóm có gì mới không",
        "thấy có mùi tiền rồi đấy",
        "cầu 1-1 à để xem nào",
        "anh em ăn sáng cả chưa",
        "bắt đầu một ngày mới với môn thể thao trí tuệ này thôi",
        "vào test thử vận may cái",
        "mới sáng đã âm vốn rồi",
        "hy vọng hôm nay trời độ",
        "thôi không nói nhiều nữa tôi vào đây",
        "ai đang đỏ cho tôi xin miếng vía",
        "cầu này lạ quá chưa thấy bao giờ",
        "để xem lịch sử phiên đã",
        "cứ phải bình tĩnh mới mong có ăn được",
        "mới sáng sớm mà căng thẳng quá",
        "vào làm vài tay khởi động nào",
        "hôm nay quyết tâm về bờ",
        "đang ngồi cafe xem cầu đây",
        "thấy có vẻ ổn áp đấy",
        "vừa vào đã thấy mùi khét rồi",
        "anh em dậy sớm kiếm lúa thế",
        "tôi theo anh em tay này nhé",
        "cầu sáng sớm thường ngắn lắm",
        "chơi thăm dò thôi",
        "cầu này có vẻ khó",
        "tôi bỏ qua ván này",
        "sáng ra đã phải suy nghĩ nhiều rồi",
        "cầu kèo nay có vẻ không đẹp lắm",
        "thôi cứ đánh nhỏ giọt đã",
        "mới húp được một tay ấm người hẳn",
        "vừa nạp tiền xong vào test luôn",
        "hôm nay phải thật kỷ luật mới được",
        "chúc anh em may mắn",
        "tôi vào trước đây có gì hay tôi báo",
        "cầu đang đi đều phết",
        "có biến rồi anh em ạ",
        "thôi xong lại gãy",
        "sáng ra đã mất tiền ngu",
        "phải tập trung hơn mới được",
        "có ai vừa theo tôi không",
        "sáng sớm mà đã thua rồi",
        "để tôi soi lại cầu đã",
        "có vẻ không ổn lắm",
        "thôi làm lại từ đầu",
        "vào vốn cẩn thận nhé anh em",
        "đừng vội vàng buổi sáng",
        "tôi thấy có dây bệt rồi đấy",
        "bắt đầu thôi",
        "vào việc cho nóng người",
        "sáng ra không khí trong lành thật",
        "vừa chạy bộ về vào xem nhóm luôn",
        "hôm nay nhất định phải thắng",
        "đang có linh cảm tốt",
        "mở bát thế này là đẹp rồi",
        "chơi từ từ thôi",
        "hôm nay có vẻ là một ngày đẹp trời",
        "tôi sẽ cẩn thận hơn hôm qua",
        "vừa vào đã thấy sôi động rồi",
        "anh em nào có cầu hay thì chia sẻ nhé",
        "tôi đang hơi phân vân",
        "có nên vào tay này không nhỉ",
        "thôi liều một phen",
        "sáng ra mà đã toát mồ hôi rồi",
        "6h30 rồi, điểm danh anh em chiến hữu.",
        "Mở mắt ra là thấy nhớ bàn cược rồi.",
        "Sáng sớm cầu chạy mượt không anh em?",
        "Làm tách trà nóng rồi vào soi cầu cho tỉnh táo.",
        "Hôm nay mục tiêu kiếm bữa sáng cafe thôi.",
        "Vừa vào làm nhẹ một tay khởi động.",
        "Anh em nào có cầu thơm thì phím tôi với nhé.",
        "Cầu sáng sớm thường hay biến động, anh em cẩn thận.",
        "Ai bắt được dây bệt từ sớm không?",
        "Bắt đầu ngày mới bằng một tay thắng cho may mắn nào.",
        "Sáng nay tôi có linh cảm tốt lắm.",
        "Vốn mỏng nên chỉ dám vào từ từ.",
        "Cứ phải quan sát vài ván rồi mới dám xuống tiền."
    ],
    # --- Kịch bản buổi trưa (12h - 13h) ---
    "noon": [
        "thôi nghỉ tay ăn cơm đã anh em",
        "sáng giờ coi như hòa vốn chiều gỡ lại",
        "ăn cơm cũng không ngon quả gãy tay cuối cay thật",
        "húp được mấy lít buổi sáng đi ăn trưa ngon mồm rồi",
        "chiều có kèo nào thơm không anh em tôi đang xa bờ quá",
        "mệt quá chợp mắt tí chiều chiến tiếp",
        "cầu trưa khó bắt thật ngồi im cho lành",
        "anh em chơi nhé tôi đi ăn cơm đã",
        "thua mấy tay thông chán không buồn ăn",
        "chốt phiên sáng tạm thế chiều tính sau",
        "nạp năng lượng thôi đói quá rồi",
        "sáng giờ gãy hơi nhiều chiều phải gỡ gạc lại",
        "được có mấy đồng bạc lẻ thôi",
        "anh em ăn trưa chưa",
        "tạm nghỉ giải lao tí",
        "căng mắt từ sáng đến giờ mệt thật",
        "bụng đói tay run không dám vào tiền",
        "chiều nay có tất tay được không anh em",
        "vừa làm bát cơm xong lại vào hóng",
        "có ai như tôi không ăn cơm mà vẫn phải cầm điện thoại xem",
        "sáng giờ loay hoay vẫn âm",
        "thôi nghỉ ngơi cho đầu óc nó minh mẫn",
        "chiều nay quyết chiến",
        "có ai tranh thủ giờ nghỉ làm vài tay không",
        "tổng kết phiên sáng lãi được đúng bữa trưa",
        "đen quá anh em ạ",
        "chiều nay mà thua nữa chắc tôi xóa app",
        "tôi đi làm về rồi giờ mới rảnh tay",
        "vừa ăn vừa xem đây",
        "chúc anh em ăn trưa ngon miệng",
        "sáng giờ có ai húp đậm không",
        "cầu kèo giờ này khó đoán lắm",
        "thôi cứ phải no cái bụng đã",
        "chiều hi vọng cầu đẹp hơn",
        "sáng giờ có tí lộc lá rồi",
        "tôi phải đi ngủ một giấc chiều mới có sức",
        "mệt mỏi thật sự",
        "thôi không ham hố nữa nghỉ thôi",
        "giờ nghỉ rồi mà nhóm vẫn xôm thế",
        "tí nữa quay lại với anh em",
        "đang ngồi quán cơm lướt nhóm đây",
        "cầu chạy ảo quá",
        "sáng giờ toàn ngồi xem là chính",
        "chiều làm lại từ đầu",
        "cứ bình tĩnh anh em ạ",
        "thua keo này ta bày keo khác",
        "tôi thấy hơi oải rồi",
        "thôi nghỉ đã không lại lú",
        "chúc anh em buổi chiều may mắn",
        "no bụng rồi giờ mới tỉnh táo được",
        "sáng nay có ai được nhiều không",
        "tôi sáng nay mất mấy lít rồi",
        "chiều phải làm lại mới được",
        "giờ nghỉ tranh thủ soi lại cầu",
        "cầu sáng nay đi khó chịu thật",
        "hy vọng chiều nó ổn định hơn",
        "tôi tạm thời không vào lệnh nữa",
        "ngồi xem cho chắc ăn",
        "anh em nào đang chơi thì cẩn thận nhé",
        "giờ này dễ bị lừa lắm",
        "tôi đi nghỉ một lúc đây",
        "lát nữa quay lại phục thù",
        "sáng giờ cũng tạm ổn",
        "kiếm được bữa trưa sang chảnh rồi",
        "thôi cứ ăn chắc mặc bền",
        "không dám ham hố nhiều",
        "tổng kết sáng nay lãi nhẹ",
        "cũng đủ tiền xăng xe rồi",
        "chiều nay lại chiến đấu tiếp",
        "anh em nghỉ ngơi đi nhé",
        "đừng căng thẳng quá",
        "thắng thua là chuyện thường",
        "quan trọng là giữ được vốn",
        "tôi đi ngủ trưa đây",
        "chiều có sức mà gỡ",
        "anh em cứ chơi vui vẻ",
        "đừng để game ảnh hưởng",
        "tôi thấy chiều nay có vẻ có biến",
        "phải cẩn thận mới được",
        "sáng giờ cũng học được mấy bài",
        "chiều sẽ áp dụng luôn",
        "thôi không nói nhiều nữa",
        "tôi đi nghỉ đây",
        "chúc anh em buổi trưa vui vẻ",
        "lát nữa gặp lại",
        "hy vọng chiều nay rực rỡ",
        "tôi tin là mình sẽ gỡ lại được",
        "quyết tâm lên",
        "anh em nào đang thua thì đừng nản",
        "cơ hội còn nhiều",
        "tôi đi nạp năng lượng đây",
        "chiều nay sẽ khác",
        "tôi hứa đấy",
        "Sáng nay tạm lãi ổ bánh mì, chiều tính tiếp.",
        "Nghỉ trưa nạp đạn chiều bắn phá nhà cái nào.",
        "Có ai ăn trưa mà vẫn đang soi cầu như tôi không?",
        "Tạm chốt phiên sáng, lãi được cốc cafe.",
        "Thôi nghỉ ngơi lấy sức, chiều gỡ lại cả vốn lẫn lãi.",
        "Cầu kèo giờ nghỉ trưa khó đoán lắm, anh em đừng vội.",
        "Ăn xong làm ván cho tiêu cơm nào.",
        "Sáng nay ai đỏ cho tôi xin vía chiều với.",
        "Đói quá, tay run không dám vào lệnh.",
        "Chúc anh em ăn trưa ngon miệng, chiều húp đậm nhé."
    ],
    # --- Kịch bản buổi chiều (15h - 17h) ---
    "afternoon": [
        "đang làm phải vào lén một tay đây",
        "chiều nay cầu đi như ma làm chả biết đường nào mà lần",
        "ngồi làm mà đầu óc toàn cầu với kèo thôi",
        "làm tay nữa kiếm tiền tối đi nhậu nào",
        "lại gãy rồi chiều nay đen quá",
        "bàn kia đang bệt kìa anh em có ai theo không",
        "chán thật cứ vào tiền là nó lại bẻ cầu",
        "sắp tan làm rồi cố vớt vát tí vốn",
        "tay này mà thua nữa là tôi nghỉ luôn",
        "có linh cảm tay này về Con anh em ạ",
        "vừa trốn sếp ra ngoài làm một tay",
        "cầu kèo buổi chiều khó chịu thật",
        "mất tập trung quá không làm được việc",
        "kiếm thêm ly trà đá thôi",
        "chiều nay có vẻ không phải ngày của tôi",
        "bàn này cầu chạy ổn định phết",
        "lại ngứa tay rồi",
        "tan làm rồi vào chiến thôi",
        "vớt vát lại được ít vốn rồi may quá",
        "tay này tôi không chắc lắm",
        "ngồi hóng cầu kèo từ nãy giờ",
        "cầu đi loạn hết cả lên",
        "có ai đang thắng không",
        "làm thêm tay chốt hạ rồi nghỉ",
        "tối nay có tiền đi chơi không là nhờ cả vào tay này",
        "cầu 1-2-3 à đẹp thế",
        "tôi vừa lỡ mất một dây ngon",
        "đen thôi đỏ quên đi",
        "anh em nào đang chơi không",
        "tôi theo anh em tay này nhé",
        "vừa bị sếp mắng xong vào đây giải đen",
        "cầu gì mà khó thế",
        "tôi bỏ qua tay này",
        "chiều nay anh em có vẻ im ắng nhỉ",
        "chắc mọi người đang bận làm",
        "tôi tranh thủ vào một lúc thôi",
        "lại thua rồi",
        "thôi chiều nay nghỉ sớm",
        "về nhà rồi mới tập trung được",
        "cầu này có vẻ thơm đấy",
        "tôi vào nhẹ tay này thôi",
        "sắp hết giờ làm việc rồi",
        "chiều nay có ai được đồng nào không",
        "tôi thấy hơi run",
        "cầu này dễ bệt lắm",
        "anh em cho xin ý kiến với",
        "thôi xong lại toang",
        "hẹn anh em buổi tối",
        "tôi đi về đã",
        "chiều nay coi như bỏ",
        "về đến nhà rồi đây",
        "bắt đầu chuyên tâm được rồi",
        "chiều nay mất tập trung quá",
        "thua mấy tay lãng xẹt",
        "tối phải gỡ lại mới được",
        "cầu chiều nay đúng là không dành cho mình",
        "có ai giống tôi không",
        "cứ chiều là lại thua",
        "chắc phải đổi giờ chơi thôi",
        "anh em tan làm cả chưa",
        "vào chiến đấu thôi",
        "chuẩn bị cho buổi tối rực rỡ nào",
        "tôi vừa tắm xong tỉnh táo hẳn",
        "giờ mới là lúc kiếm tiền",
        "ban ngày chơi không hiệu quả",
        "tôi thấy có cầu mới rồi",
        "để tôi vào xem thử",
        "có vẻ ngon ăn đấy",
        "anh em vào đi",
        "đừng bỏ lỡ cơ hội này",
        "tôi vào trước đây",
        "húp rồi anh em ơi",
        "thấy chưa tôi bảo rồi mà",
        "chiều nay thế là đủ rồi",
        "chốt lãi nghỉ sớm thôi",
        "không nên tham quá",
        "biết đủ là hạnh phúc",
        "tôi đi lo việc nhà đây",
        "tối quay lại với anh em sau",
        "chúc anh em buổi chiều vui vẻ",
        "kiếm được nhiều lúa nhé",
        "tôi đi đón con đã",
        "lát nữa chơi tiếp",
        "chiều nay thế là ấm rồi",
        "đủ tiền ăn tối rồi",
        "cảm ơn anh em đã đồng hành",
        "tối lại gặp nhau nhé",
        "tôi đi chợ đây",
        "mua mồi ngon về nhậu",
        "chiều nay may mắn thật",
        "hy vọng tối cũng thế",
        "tôi phải đi tập thể dục đã",
        "giữ gìn sức khỏe còn chiến đấu lâu dài",
        "anh em đừng quên nhé",
        "thôi chào anh em",
        "tối gặp lại",
        "Vừa họp vừa soi cầu, đúng là đam mê.",
        "Sắp tan làm rồi, ngứa tay quá anh em ạ.",
        "Cầu chiều nay đi khó chịu thật sự.",
        "Làm ván giải ngố sau giờ làm việc căng thẳng.",
        "Vừa tan làm là phải vào nhóm xem tình hình ngay.",
        "Chiều nay có vẻ êm đềm hơn sáng.",
        "Có ai đang bắt được dây bệt chiều không?",
        "Làm tay cuối kiếm tiền đổ xăng về nhà nào.",
        "Về đến nhà rồi, giờ mới toàn tâm toàn ý được.",
        "Anh em chuẩn bị cho phiên tối chưa?"
    ],
    # --- Kịch bản buổi tối (20h - 22h) ---
    "evening": [
        "cơm nước xong rồi giờ mới tập trung được",
        "tối nay phải gỡ lại hết những gì đã mất",
        "vào phát bú ngay tay đầu tối nay hên rồi",
        "anh em đâu hết rồi lên cho xôm nào",
        "cầu 1-1 đẹp thế nhờ đừng gãy lúc này nhé",
        "cay vãi tay kết nhất thì lại toang",
        "tôi định vào mạnh tay này có ai theo không",
        "nhóm có ai đang đỏ không cho tôi xin ít vía",
        "mạng lag đúng cái lúc nặn bài bực thật",
        "thôi xong lại một dây đen toang thật rồi",
        "giờ vàng đến rồi anh em ơi",
        "quyết chiến đêm nay",
        "vừa vào đã thấy không khí khác hẳn",
        "tối nay cầu kèo có vẻ nét hơn",
        "tập trung bắt quả cầu bệt này thôi",
        "vừa vào một tay mà tim nhảy ra ngoài",
        "may quá nó về thật hú hồn",
        "cứ tay nào mình vào to là y như rằng gãy",
        "anh em cổ vũ cho tôi cái nào",
        "tối nay mà thua nữa chắc tôi trầm cảm",
        "lên đồ chiến đấu thôi",
        "tôi đã sẵn sàng",
        "cầu kèo tối nay trông có vẻ hứa hẹn",
        "vừa làm được một dây thông phê thật",
        "đừng ai bẻ cầu của tôi nhé",
        "đen quá đi mất",
        "tôi đang hơi cay cú rồi đấy",
        "bình tĩnh lại nào",
        "tối nay phải thật kỷ luật",
        "có ai đang chung thuyền với tôi không",
        "cầu đi khó đoán quá",
        "tôi đang ngồi soi lại lịch sử",
        "tay này 50 50 quá",
        "liều ăn nhiều thôi",
        "chúc anh em buổi tối rực rỡ",
        "tôi bắt đầu đây",
        "cầu này đẹp quá phải vào ngay",
        "lại thua rồi chán thật",
        "tối nay có vẻ không ổn",
        "tôi tạm nghỉ xem xét đã",
        "anh em nào có kinh nghiệm chỉ tôi với",
        "cầu đang có dấu hiệu bẻ",
        "tôi theo cầu đến cùng luôn",
        "húp rồi anh em ơi",
        "cảm giác thật tuyệt vời",
        "tối nay ấm rồi",
        "lại có tiền tiêu rồi",
        "đang trên đà chiến thắng",
        "không được chủ quan",
        "tối nay phải về bờ mới được",
        "anh em cùng tôi chiến đấu nhé",
        "đừng để nhà cái nó lừa",
        "phải tỉnh táo lên",
        "tôi thấy có mùi rồi đấy",
        "tay này chắc chắn về",
        "anh em tin tôi đi",
        "tôi đã phân tích rất kỹ rồi",
        "vào thôi còn chờ gì nữa",
        "thấy chưa tôi nói có sai đâu",
        "lại húp tiếp rồi",
        "tối nay là của tôi",
        "không ai cản được tôi đâu",
        "tôi đang rất tự tin",
        "anh em cứ theo tôi mà đánh",
        "đảm bảo có lãi",
        "đừng sợ",
        "chơi là phải có bản lĩnh",
        "thắng không kiêu bại không nản",
        "tôi đang áp dụng đúng như thế",
        "và nó đang hiệu quả",
        "cảm ơn anh em đã tin tưởng",
        "chúng ta cùng nhau chiến thắng",
        "đánh sập nhà cái thôi",
        "tối nay phải cho nó biết tay",
        "đừng tưởng dễ ăn của tôi",
        "tôi đã có kinh nghiệm rồi",
        "không dễ bị lừa đâu",
        "anh em cứ yên tâm",
        "tôi sẽ dẫn dắt anh em về bờ",
        "hứa đấy",
        "tối nay không về bờ không ngủ",
        "quyết tâm cao độ",
        "anh em cùng hô khẩu hiệu nào",
        "chiến thắng",
        "tôi đang rất hưng phấn",
        "cầu đang đi đúng ý tôi",
        "không thể tuyệt vời hơn",
        "cảm ơn cuộc đời",
        "tối nay tôi sẽ có một giấc ngủ ngon",
        "Giờ hoàng đạo đã điểm, anh em lên thuyền!",
        "Tối nay quyết khô máu với nhà cái.",
        "Anh em ăn tối cả chưa, vào việc thôi.",
        "Cầu tối nay có vẻ dễ bắt hơn ban ngày.",
        "Làm vài tay kiếm tiền mai đi chợ nào.",
        "Tối nay là cơ hội để gỡ lại những gì đã mất.",
        "Ai đang xa bờ thì bơi vào đây với tôi.",
        "Tập trung cao độ, không để nhà cái lừa.",
        "Tay này tôi rất kết, anh em theo không?",
        "Vừa húp được một dây thông, sướng rơn người.",
        "Tối nay mà thắng lớn mai tôi mời cả nhóm cafe.",
        "Cầu đang đi đẹp, hy vọng không gãy đột ngột."
    ],
    # --- Kịch bản đêm khuya (Sau 23h) ---
    "late_night": [
        "khuya rồi càng chơi càng cay thôi tôi nghỉ",
        "chúc anh em ở lại may mắn tôi đi ngủ mai gỡ",
        "nốt tay này thôi thắng thua gì cũng nghỉ",
        "lại một đêm phải ăn mì tôm chán đời",
        "may quá hôm nay chốt lãi được ít ngủ ngon rồi",
        "đêm cầu kèo khó chơi thật hay do nhà cái nó bịp",
        "mắt díp cả vào rồi thôi chào anh em tôi off",
        "cố từ tối đến giờ vẫn âm nản quá",
        "có ai còn thức không nói chuyện cho đỡ buồn",
        "phải tắt máy thôi không mai lại không có gì vào mồm",
        "buồn ngủ quá rồi",
        "thôi hôm nay chốt lỗ đi ngủ",
        "càng đêm càng cuốn",
        "kỷ luật là sức mạnh",
        "hẹn gặp lại anh em vào ngày mai",
        "lại một đêm xa bờ",
        "chán chẳng buồn nói",
        "chúc anh em ngủ ngon",
        "tôi xin phép dừng cuộc chơi tại đây",
        "mệt mỏi rã rời",
        "cố quá lại thành quá cố",
        "thôi nay thế thôi",
        "đầu óc lú hết cả rồi",
        "mai làm lại từ đầu",
        "càng gỡ càng thua",
        "đến giờ đi ngủ rồi",
        "anh em nào còn chơi thì vững tay nhé",
        "tôi chịu hết nổi rồi",
        "hôm nay thế là ấm rồi đủ chỉ tiêu",
        "dừng đúng lúc cũng là một chiến thắng",
        "khuya rồi còn ai không",
        "tôi chơi nốt ván này rồi nghỉ",
        "đêm là lúc dễ mất bình tĩnh nhất",
        "phải giữ cái đầu lạnh",
        "thua nhiều quá rồi",
        "tổng kết ngày hôm nay âm nặng",
        "mai không biết lấy gì ăn",
        "thôi đi ngủ cho quên sầu",
        "cảm ơn anh em đã trò chuyện",
        "tắt máy đi ngủ thôi",
        "đêm nay lại khó ngủ rồi",
        "sức khỏe là vàng anh em ạ",
        "đừng để game ảnh hưởng cuộc sống",
        "tôi mệt rồi",
        "chào cả nhà nhé",
        "hẹn ngày mai gỡ lại",
        "đêm nay thật tồi tệ",
        "cầu kèo đêm khó bắt quá",
        "thôi tôi xin hàng",
        "giờ này chỉ có ma chơi thôi",
        "tôi đi ngủ đây",
        "mai còn phải đi làm",
        "không thể thức khuya hơn được nữa",
        "anh em giữ gìn sức khỏe nhé",
        "đừng như tôi",
        "thua đau quá",
        "mất hết cả vốn lẫn lãi",
        "ngày mai biết sống sao đây",
        "chán nản thật sự",
        "tôi không còn gì để nói nữa",
        "thôi chào anh em",
        "tôi đi đây",
        "đừng ai tìm tôi nữa",
        "tôi cần thời gian để suy nghĩ lại",
        "về cuộc đời mình",
        "về những sai lầm đã qua",
        "tôi đã sai thật rồi",
        "không nên lao vào con đường này",
        "giờ hối hận cũng đã muộn",
        "thôi số phận đã an bài",
        "tôi chấp nhận",
        "chúc anh em ở lại may mắn",
        "và đừng đi vào vết xe đổ của tôi",
        "hãy tỉnh táo lên",
        "đừng để lòng tham che mờ lý trí",
        "đó là lời khuyên chân thành của tôi",
        "một kẻ thất bại",
        "thôi tôi đi ngủ đây",
        "hy vọng sáng mai trời sẽ sáng hơn",
        "và tôi sẽ tìm được một con đường mới",
        "cho cuộc đời mình",
        "cảm ơn anh em đã lắng nghe",
        "tạm biệt",
        "Thêm một đêm mất ngủ vì nến.",
        "Thôi đóng bảng điện đi ngủ, mai còn sức cày cuốc.",
        "Càng về đêm càng khó chơi, tôi xin phép nghỉ trước.",
        "Chốt sổ hôm nay, may mà vẫn có lãi.",
        "Hôm nay đen quá, tôi đi ngủ sớm lấy lại tinh thần.",
        "Anh em nào còn chiến đấu thì may mắn nhé, tôi ngủ đây.",
        "Đêm khuya rồi, chơi dễ mất kiểm soát lắm.",
        "Hẹn gặp lại anh em vào sáng mai.",
        "Thôi dừng thôi, không lại bay hết thành quả cả ngày.",
        "Một ngày mệt mỏi, chúc anh em ngủ ngon."
    ],
    # --- Kịch bản tự vấn / Than thở ---
    "experience_motivation": [
        "lại tự mình hại mình rồi đáng lẽ ăn non là nghỉ",
        "cái tội tham muôn đời không chừa được",
        "biết là phải dừng mà tay nó cứ bấm thôi",
        "hôm nay lại thua không biết bao giờ mới về bờ",
        "cảm giác cay cú này khó chịu thật",
        "bình tĩnh lại nào càng nóng càng thua thôi",
        "sao người ta thắng suốt mà mình cứ thua mãi nhỉ",
        "hôm nay quyết không gấp thếp xem sao",
        "lại thêm một bài học nữa đừng bao giờ tất tay",
        "nhiều lúc muốn bỏ hẳn đi cho nhẹ nợ",
        "lại là tôi của ngày hôm qua",
        "cứ cố gỡ là lại đi xa hơn",
        "giờ thì ngồi nhìn tài khoản",
        "tôi cũng chịu tôi rồi",
        "mất tiền bạc cả người",
        "phải giữ kỷ luật mới mong bền được",
        "kinh nghiệm xương máu đấy",
        "đừng bao giờ vào lệnh khi tâm trạng không tốt",
        "lại một bài học đắt giá",
        "hôm nào thấy đen quá thì nên nghỉ",
        "đừng cố đấm ăn xôi",
        "thua keo này ta bày keo khác",
        "quan trọng là phải giữ được vốn",
        "cơ hội không thiếu đâu",
        "chơi cái này phải kiên nhẫn",
        "đừng để cảm xúc chi phối",
        "lại phải tự kiểm điểm bản thân rồi",
        "cứ thắng được một tí là lại chủ quan",
        "bài học này sao học mãi không thuộc",
        "chán cái tính cờ bạc của mình quá",
        "lại phải đi vay tiền để gỡ rồi",
        "càng chơi càng thấy mình ngu",
        "phải thay đổi cách chơi thôi",
        "không thể mãi thế này được",
        "lại một lần nữa tin vào linh cảm và sai",
        "cái giá phải trả đắt quá",
        "thôi tự an ủi mình vậy",
        "ngày mai sẽ khác",
        "phải sốc lại tinh thần thôi",
        "thua là một phần của cuộc chơi mà",
        "quan trọng là học được gì sau mỗi lần thua",
        "lại phải bắt đầu lại từ đầu",
        "cảm giác bất lực thật",
        "lần này tôi sẽ cẩn thận hơn",
        "phải có kế hoạch rõ ràng",
        "không chơi theo cảm tính nữa",
        "lại phải ăn mì cả tháng rồi",
        "đúng là không nên ham hố",
        "tự hứa với lòng lần cuối",
        "lại tự tay bóp dái rồi",
        "đáng lẽ ra nên dừng lại",
        "tại sao mình lại ngu thế nhỉ",
        "cứ nghĩ là sẽ gỡ được",
        "ai ngờ lại lún sâu hơn",
        "thôi xong rồi",
        "mất hết rồi",
        "không còn gì nữa",
        "ngày mai biết lấy gì mà ăn",
        "chắc phải bán nhà thôi",
        "vợ con biết thì sao đây",
        "tôi phải làm gì bây giờ",
        "ai cứu tôi với",
        "tôi bế tắc quá",
        "không lối thoát",
        "chắc chỉ có cái chết mới giải thoát được cho tôi",
        "nhưng tôi không thể",
        "tôi còn gia đình",
        "tôi phải sống",
        "phải làm lại từ đầu",
        "dù khó khăn đến mấy",
        "tôi cũng sẽ không bỏ cuộc",
        "tôi sẽ chứng minh cho mọi người thấy",
        "tôi không phải là một kẻ thất bại",
        "tôi sẽ làm được",
        "chắc chắn là như vậy",
        "tôi phải mạnh mẽ lên",
        "vì gia đình",
        "vì tương lai",
        "tôi sẽ không gục ngã đâu",
        "chờ đấy",
        "tôi sẽ quay trở lại",
        "và lợi hại hơn xưa",
        "haha",
        "tôi điên rồi",
        "thật sự điên rồi",
        "thôi kệ",
        "điên cũng được",
        "miễn là tôi vẫn còn sống",
        "và còn hy vọng",
        "Cờ bạc không bao giờ là dễ dàng.",
        "Thắng không tự mãn, thua không nản lòng, đó mới là cao thủ.",
        "Lòng tham là kẻ thù lớn nhất.",
        "Chỉ một phút mất bình tĩnh là trả giá đắt.",
        "Phải học cách chấp nhận thất bại và đứng lên.",
        "Kiếm tiền đã khó, giữ tiền còn khó hơn.",
        "Đừng bao giờ để con bạc át đi con người.",
        "Mỗi lần thua là một lần học được thêm kinh nghiệm.",
        "Hôm nay có thể thua, nhưng ngày mai phải gỡ lại.",
        "Anh em nào đang thua thì đừng nản, cơ hội luôn còn ở phía trước.",
        "Cờ bạc là bộ môn của tâm lý và kỷ luật.",
        "Hãy coi đây là một cuộc đầu tư, không phải một trò may rủi."
    ],
    # --- Kịch bản tương tác / Đặt câu hỏi ---
    "interaction": [
        "cầu này nên theo hay bẻ đây anh em",
        "phân vân quá ai cho tôi lời khuyên với",
        "có ai đang ở bàn 8 không cầu bên đấy thế nào",
        "Cái nhé anh em ai chung thuyền không",
        "vừa gãy tay to có nên vào gỡ lại ngay không",
        "nhóm nay im thế không ai chơi à",
        "anh em nào đang húp lên tiếng cái cho có động lực",
        "bàn này có bịp không anh em tôi thua thông mấy tay rồi",
        "mọi người hay soi cầu kiểu gì thế",
        "tay này về Con tôi tin cầu sẽ đi 2-2",
        "cầu bệt Player 4 tay rồi có nên theo tiếp không",
        "tay này tôi kết cửa Banker quá",
        "sao đen thế nhỉ tôi đánh bên nào bên đấy thua",
        "ván này khó quá tôi bỏ qua",
        "anh em nào bắt được thì cho tôi xin vía",
        "có cao nhân nào trong nhóm không cho xin ít nhận định",
        "tôi đang hơi loạn cầu rồi",
        "anh em thấy tay tiếp theo nên đi đâu",
        "nhóm mình dạo này có vẻ trầm nhỉ",
        "ai thắng thì lên tiếng cho có không khí với nào",
        "bàn này có vẻ đang bệt đây",
        "anh em nào theo không cho tôi thêm tự tin",
        "ui nhà cái vừa ra đôi 9 có điềm gì không các bác",
        "tình hình có vẻ hơi khó đoán",
        "ai có thể chia sẻ một vài phân tích không",
        "cầu đang đi 1-1 đẹp thế",
        "có ai đang chung thuyền cửa Player với tôi không",
        "vào cổ vũ cho nhau cái nào",
        "bàn này cầu xấu quá tôi qua bàn khác đây",
        "anh em đang chơi ở sảnh nào thế",
        "có nên nuôi cửa Hòa không nhỉ",
        "tay này tất tay được không anh em",
        "tôi đang cần một sự trợ giúp",
        "ai có kinh nghiệm soi cầu chỉ giáo với",
        "cầu này có mùi bẻ lắm",
        "anh em nghĩ sao về tay này",
        "có ai dám theo tôi tay này không",
        "tôi thấy cầu này quen quen",
        "nhóm mình có ai hay chơi đêm không",
        "sao không thấy ai nói gì vậy",
        "tôi đơn độc quá",
        "cầu đang đi đúng như dự đoán",
        "anh em thấy tôi phán chuẩn không",
        "có nên tin vào linh cảm không nhỉ",
        "ván này tôi không chắc chắn lắm",
        "ai đó cho tôi một điểm tựa đi",
        "bàn này chơi ổn không anh em",
        "cầu này có vẻ dễ bắt",
        "tôi nên vào bao nhiêu vốn tay này",
        "giúp tôi với anh em ơi",
        "có ai ở đây không",
        "tương tác đi nào",
        "buồn quá",
        "chơi một mình không vui",
        "anh em đâu hết rồi",
        "lên tiếng đi chứ",
        "đừng để tôi cô đơn",
        "cùng nhau thảo luận đi",
        "để tìm ra cầu đẹp",
        "chiến thắng nhà cái",
        "anh em có đồng ý không",
        "nếu đồng ý thì cho tôi một tràng pháo tay nào",
        "haha",
        "tôi đùa thôi",
        "nhưng mà tương tác đi nhé",
        "để nhóm mình sôi động hơn",
        "và chúng ta sẽ có nhiều thông tin hơn",
        "để đưa ra quyết định chính xác",
        "cảm ơn anh em",
        "tôi tin là chúng ta sẽ làm được",
        "cùng nhau chúng ta sẽ chiến thắng",
        "chắc chắn là như vậy",
        "tôi yêu anh em",
        "haha",
        "lại sến rồi",
        "thôi tôi đi soi cầu đây",
        "có gì hay tôi sẽ báo",
        "anh em cứ chờ tin tốt của tôi nhé",
        "tôi sẽ không làm anh em thất vọng đâu",
        "hứa đấy",
        "yêu thương",
        "haha",
        "thôi đi đây",
        "không lại bị chửi là khùng",
        "tạm biệt nhé",
        "lát nữa gặp lại",
        "yêu cả nhà",
        "Cầu này có vẻ khó, anh em có cao kiến gì không?",
        "Theo anh em tay này nên vào bao nhiêu % vốn?",
        "Có ai đang theo dõi bàn 6 không, cầu bên đó thế nào rồi?",
        "Tay này tôi đặt niềm tin vào cửa Banker, ai theo không?",
        "Bệt 5 tay rồi, có nên bẻ không anh em?",
        "Nhóm mình có ai là chuyên gia soi cầu không, cho tôi xin ít lời khuyên.",
        "Tình hình anh em hôm nay thế nào rồi?",
        "Sao dạo này nhóm ít tương tác thế nhỉ, anh em lên tiếng đi cho xôm.",
        "Ai có phương pháp quản lý vốn hay thì chia sẻ cho mọi người với.",
        "Tay này tôi không chắc lắm, có ai có nhận định gì không?",
        "Mọi người thường dùng chỉ báo nào để soi cầu thế?",
        "Có ai biết sảnh nào đang có cầu đẹp không?"
    ]
}